# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Lachlan Robertson - Fullstack Developer (Contractor)
description: "A fullstack software contractor always looking for bigger and better projects"
keywords: "developer, software, fullstack, contractor, web, WordPress, SEO, optimisation"
url: https://lrobet142.github.io/
baseurl: ""

disqus_site_shortname: "lachlan.robertson"

# Author settings
author:
  name: Lachlan Robertson
  job: Fullstack Developer (Contractor)
  bio: "No challenge too big, no project too much. Frontend or backend, when it gets done, it gets done right the first time."
  thumb: /images/author.jpg
  email: lachlan.robertson142@gmail.com
  url: https://lrobet142.github.io/
  github: https://github.com/lrobert142
  facebook: https://www.facebook.com/lachlan.robertson.754
  linkedin: https://www.linkedin.com/in/lachlan-robertson-31238377/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
