# General settings
email: lachlan.robertson142@gmail.com

# SEO settings
title: Lachlan Robertson - Fullstack Developer
description: "A fullstack software contractor always looking for bigger and better projects"
keywords: "developer, software, fullstack, contractor, web, WordPress, SEO, optimisation"
url: https://lrobet142.github.io/
baseurl: ""


# Author settings
author_data:
  name: Lachlan Robertson
  job: Fullstack Developer
  bio: "No challenge too big, no project too much. Frontend or backend, when it gets done, it gets done right <strong>the first time.</strong>"
  avatar: /assets/images/avatar.jpg
  github_username:  lrobert142
  linkedin_username: lachlan-robertson-31238377
  facebook_username: lachlan.robertson.754

# Header settings
header_pages:
  - about

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
